type  EventCode = 
  | "PACKAGE_CREATED"
  | "TICKET_CREATED"
  | "TICKET_REPLY_CREATED"
  | "DEPOSIT_BDL_CREATED"
  | "RATE_BDL_USD"
  | "TRADE_CREATED"
  | "TRADE_CREATED_NOTIFY_USER"
  | "ORDER_SUCCESS"
  | "ORDER_CREATED"
  | "ORDER_UPDATED"
  | "ORDER_CANCELED"
  ;
  
export default EventCode;
